### ISSUE TITLE
cubietruck: ERROR: A10: open failed. (-4)

### ISSUE THREAD

**Issue by vitalogy** [OpenBricks/openbricks#38]
I have no hardware acceleration when running xbmc on my cubietruck.
The following error appears in the xbmc.log every time the cubietruck should play a video (remote: 
**ERROR: A10: open failed. (-4)**
Playing videos falls back to software acceleration ... the video is sometimes jerking by at near 100% cpu usage.

here ist a debug log playing big buck bunny from sdcard:
>11:29:13 T:3046076416   DEBUG: GetMovieId (/media/big_buck_bunny_720p_surround.avi), query = select idMovie from movie where idFile=4
11:29:13 T:3046076416   DEBUG: GetEpisodeId (/media/big_buck_bunny_720p_surround.avi), query = select idEpisode from episode where idFile=4
11:29:13 T:3046076416   DEBUG: GetMusicVideoId (/media/big_buck_bunny_720p_surround.avi), query = select idMVideo from musicvideo where idFile=4
11:29:13 T:3046076416   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
11:29:13 T:3046076416   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
11:29:13 T:3046076416   DEBUG: CPlayerCoreFactory::GetPlayers(/media/big_buck_bunny_720p_surround.avi)
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtv
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: hdhomerun/myth/mms/udp
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
11:29:13 T:3046076416   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
11:29:13 T:3046076416   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
11:29:13 T:3046076416   DEBUG: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (1)
11:29:13 T:3046076416   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
11:29:13 T:3046076416   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
11:29:13 T:3046076416   DEBUG: CPlayerCoreFactory::GetPlayers: adding player: DVDPlayer (1)
11:29:13 T:3046076416   DEBUG: CPlayerCoreFactory::GetPlayers: added 1 players
11:29:13 T:3046076416  NOTICE: DVDPlayer: Opening: /media/big_buck_bunny_720p_surround.avi
11:29:13 T:3046076416 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
11:29:13 T:3046076416   DEBUG: CRenderManager::UpdateDisplayLatency - Latency set to 0 msec
11:29:13 T:3046076416   DEBUG: LinuxRendererGL: Cleaning up GL resources
11:29:13 T:2968212576  NOTICE: Thread DVDPlayer start, auto delete: false
11:29:13 T:2968212576  NOTICE: Creating InputStream
11:29:13 T:2968212576   DEBUG: ScanForExternalSubtitles: Searching for subtitles...
11:29:13 T:2968212576   DEBUG: ScanForExternalSubtitles: END (total time: 1 ms)
11:29:13 T:2968212576  NOTICE: Creating Demuxer
11:29:13 T:2968212576   DEBUG: Open - probing detected format [avi]
11:29:14 T:2968212576   DEBUG: Open - avformat_find_stream_info starting
11:29:14 T:2968212576   DEBUG: Open - av_find_stream_info finished
11:29:14 T:2968212576    INFO: ffmpeg[B0EB5460]: Input #0, avi, from '/media/big_buck_bunny_720p_surround.avi':
11:29:14 T:2968212576    INFO: ffmpeg[B0EB5460]:   Metadata:
11:29:14 T:2968212576    INFO: ffmpeg[B0EB5460]:     encoder         : AVI-Mux GUI 1.17.7, Aug  8 2006  20:59:17
11:29:14 T:2968212576    INFO: ffmpeg[B0EB5460]:     JUNK            :
11:29:14 T:2968212576    INFO: ffmpeg[B0EB5460]:   Duration: 00:09:56.46, start: 0.000000, bitrate: 4456 kb/s
11:29:14 T:2968212576    INFO: ffmpeg[B0EB5460]:     Stream #0:0: Video: mpeg4 (Simple Profile) (FMP4 / 0x34504D46), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 24 tbr, 24 tbn, 24 tbc
11:29:14 T:2968212576    INFO: ffmpeg[B0EB5460]:     Stream #0:1: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, 5.1(side), fltp, 448 kb/s
11:29:14 T:2968212576    INFO: ffmpeg[B0EB5460]:     Metadata:
11:29:14 T:2968212576    INFO: ffmpeg[B0EB5460]:       title           : BBB-Master
11:29:14 T:2968212576   DEBUG: CDVDDemuxFFmpeg::AddStream(0, ...) -> 0
11:29:14 T:2968212576   DEBUG: CDVDDemuxFFmpeg::AddStream(1, ...) -> 1
11:29:14 T:2968212576  NOTICE: Opening video stream: 0 source: 256
11:29:14 T:2968212576  NOTICE: Creating video codec with codec id: 13
11:29:14 T:2968212576   DEBUG: CDVDFactoryCodec: compiled in hardware support: CrystalHD:no AMCodec:no MediaCodec:no OpenMax:no libstagefright:no VDPAU:no VAAPI:no
11:29:14 T:2968212576   DEBUG: FactoryCodec - Video: A10 - Opening
11:29:14 T:2968212576  NOTICE: A10: using hardware rendering.
11:29:14 T:2968212576   DEBUG: A10: MEDIAINFO: fpsrate 24 / fpsscale 1
11:29:14 T:2968212576   DEBUG: A10: MEDIAINFO: Framerate 24000
11:29:14 T:2968212576   DEBUG: A10: MEDIAINFO: Frame Duration 41666
11:29:14 T:2968212576   DEBUG: A10: MEDIAINFO: CodecID 13
11:29:14 T:2968212576   DEBUG: A10: MEDIAINFO: StreamType 2
11:29:14 T:2968212576   DEBUG: A10: MEDIAINFO: Level 1
11:29:14 T:2968212576   DEBUG: A10: MEDIAINFO: Profile 0
11:29:14 T:2968212576   DEBUG: A10: MEDIAINFO: PTS_invalid 0
11:29:14 T:2968212576   DEBUG: A10: MEDIAINFO: Tag 877677894
11:29:14 T:2968212576   DEBUG: A10: MEDIAINFO: Tag fourcc FMP4
11:29:14 T:2968212576   DEBUG: A10: MEDIAINFO: extradata 45 000001b001000001b58913000001000000012000c48d8800c528045a1463000001b24c61766335312e34342e30
11:29:14 T:2968212576  NOTICE: A10: CEDARV_FORMAT: 2
11:29:14 T:2968212576  NOTICE: A10: CEDARV_SUBFORMAT: 3
11:29:14 T:2968212576  NOTICE: A10: CEDARV_CONTAINERFORMAT: 0
11:29:14 T:2968212576   DEBUG: A10: cedar not in use yet
11:29:14 T:2968212576   DEBUG: A10: cedar initialized
11:29:14 T:2968212576   DEBUG: A10: vstream_info set
11:29:14 T:2968212576   ERROR: A10: open failed. (-4)
11:29:14 T:2968212576   DEBUG: A10: cedar dispose.
11:29:14 T:2968212576   DEBUG: FactoryCodec - Video: A10 - Failed
11:29:14 T:2968212576   DEBUG: FactoryCodec - Video:  - Opening
11:29:14 T:2968212576  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: MPEG-4 part 2
11:29:14 T:2968212576   DEBUG: FactoryCodec - Video: ff-mpeg4 - Opened
11:29:14 T:2968212576  NOTICE: Creating video thread
11:29:14 T:2959823968  NOTICE: Thread DVDPlayerVideo start, auto delete: false
11:29:14 T:2959823968  NOTICE: running thread: video_thread
11:29:14 T:2968212576  NOTICE: Opening audio stream: 1 source: 256
11:29:14 T:2968212576  NOTICE: Finding audio codec for: 86019
11:29:14 T:2959823968   DEBUG: CDVDPlayerVideo - CDVDMsg::GENERAL_SYNCHRONIZE
11:29:14 T:2968212576   DEBUG: FactoryCodec - Audio: passthrough - Opening
11:29:14 T:2968212576   DEBUG: FactoryCodec - Audio: passthrough - Failed
11:29:14 T:2968212576   DEBUG: FactoryCodec - Audio: FFmpeg - Opening
11:29:14 T:2968212576   DEBUG: FactoryCodec - Audio: FFmpeg - Opened
11:29:14 T:2968212576  NOTICE: Creating audio thread
11:29:14 T:2884416608  NOTICE: Thread DVDPlayerAudio start, auto delete: false
11:29:14 T:2968212576   DEBUG: ReadEditDecisionLists - Checking for edit decision lists (EDL) on local drive or remote share for: /media/big_buck_bunny_720p_surround.avi
11:29:14 T:2968212576   DEBUG: OnPlayBackStarted : play state was 1, starting 1
11:29:14 T:2968212576   DEBUG: CDVDPlayer::SetCaching - caching state 3
11:29:14 T:3046076416   DEBUG: PlayFile : OpenFile succeed, play state 2
11:29:14 T:3046076416   DEBUG: OnPlayBackStarted : play state was 2, starting 0
11:29:14 T:2884416608  NOTICE: running thread: CDVDPlayerAudio::Process()
11:29:14 T:2959823968    INFO: CDVDPlayerVideo - Stillframe left, switching to normal playback
11:29:14 T:2884416608  NOTICE: Creating audio stream (codec id: 86019, channels: 6, sample rate: 48000, no pass-through)
11:29:14 T:3033527392    INFO: CActiveAESink::OpenSink - initialize sink
11:29:14 T:3033527392   DEBUG: CActiveAESink::OpenSink - trying to open device ALSA:hdmi:CARD=sunxisndhdmi,DEV=0
11:29:14 T:3033527392   DEBUG: CAESinkALSA::GetChannelLayout - Input Channel Count: 2 Output Channel Count: 2
11:29:14 T:3033527392   DEBUG: CAESinkALSA::GetChannelLayout - Requested Layout: FL,FR
11:29:14 T:3033527392   DEBUG: CAESinkALSA::GetChannelLayout - Got Layout: FL,FR
11:29:14 T:3033527392    INFO: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=sunxisndhdmi,DEV=0"
11:29:14 T:2884416608   DEBUG: CDVDPlayerAudio:: synctype set to 0: clock feedback
11:29:14 T:3033527392    INFO: CAESinkALSA::Initialize - Opened device "hdmi:CARD=sunxisndhdmi,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x02"
11:29:14 T:3033527392    INFO: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
11:29:14 T:3033527392    INFO: CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE
11:29:14 T:3033527392   DEBUG: CAESinkALSA::InitializeHW - Request: periodSize 2400, bufferSize 9600
11:29:14 T:3033527392   DEBUG: CAESinkALSA::InitializeHW - Got: periodSize 2400, bufferSize 9600
11:29:14 T:3033527392   DEBUG: CAESinkALSA::InitializeHW - Setting timeout to 200 ms
11:29:14 T:3033527392   DEBUG: CAESinkALSA::GetChannelLayout - Input Channel Count: 2 Output Channel Count: 2
11:29:14 T:3033527392   DEBUG: CAESinkALSA::GetChannelLayout - Requested Layout: FL,FR
11:29:14 T:3033527392   DEBUG: CAESinkALSA::GetChannelLayout - Got Layout: FL,FR
11:29:14 T:3033527392   DEBUG: CActiveAESink::OpenSink - ALSA Initialized:
11:29:14 T:3033527392   DEBUG:   Output Device : sunxi-sndhdmi
11:29:14 T:3033527392   DEBUG:   Sample Rate   : 48000
11:29:14 T:3033527392   DEBUG:   Sample Format : AE_FMT_S32NE
11:29:14 T:3033527392   DEBUG:   Channel Count : 2
11:29:14 T:3033527392   DEBUG:   Channel Layout: FL,FR
11:29:14 T:3033527392   DEBUG:   Frames        : 2400
11:29:14 T:3033527392   DEBUG:   Frame Samples : 4800
11:29:14 T:3033527392   DEBUG:   Frame Size    : 8
11:29:14 T:3043964000   DEBUG: CActiveAE::ClearDiscardedBuffers - buffer pool deleted
11:29:14 T:2968212576   DEBUG: Previous line repeats 1 times.
11:29:14 T:2968212576   DEBUG: CDVDPlayer::HandleMessages - player started 1
11:29:14 T:2959823968  NOTICE:  fps: 24.000000, pwidth: 1280, pheight: 720, dwidth: 1280, dheight: 720
11:29:14 T:2959823968   DEBUG: OutputPicture - change configuration. 1280x720. framerate: 24.00. format: YV12
11:29:14 T:2959823968  NOTICE: Display resolution DESKTOP : 1920x1080 @ 60.00 - Full Screen (16)
11:29:14 T:2959823968   DEBUG: CXBMCRenderManager::Configure - 3
11:29:14 T:3046076416  NOTICE: Using GL_TEXTURE_2D
11:29:14 T:3046076416   DEBUG: GL: Requested render method: 0
11:29:14 T:3046076416   DEBUG: GL: BaseYUV2RGBGLSLShader: defines:
                                            #define XBMC_YV12
11:29:14 T:3046076416  NOTICE: GL: Selecting Single Pass YUV 2 RGB shader
11:29:14 T:3046076416   DEBUG: GL: Vertex Shader compilation log:
11:29:14 T:3046076416   DEBUG: GL: Vertex Shader compiled successfully
11:29:14 T:3046076416   DEBUG: GL: Pixel Shader compilation log:
11:29:14 T:3046076416   DEBUG: GL: Fragment Shader compiled successfully
11:29:14 T:3046076416  NOTICE: GL: NPOT texture support detected
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 1280 x 720
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 640 x 360
11:29:14 T:3046076416   DEBUG: Previous line repeats 1 times.
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 1280 x 360
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 640 x 180
11:29:14 T:3046076416   DEBUG: Previous line repeats 1 times.
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 1280 x 360
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 640 x 180
11:29:14 T:3046076416   DEBUG: Previous line repeats 1 times.
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 1280 x 720
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 640 x 360
11:29:14 T:3046076416   DEBUG: Previous line repeats 1 times.
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 1280 x 360
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 640 x 180
11:29:14 T:3046076416   DEBUG: Previous line repeats 1 times.
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 1280 x 360
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 640 x 180
11:29:14 T:3046076416   DEBUG: Previous line repeats 1 times.
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 1280 x 720
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 640 x 360
11:29:14 T:3046076416   DEBUG: Previous line repeats 1 times.
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 1280 x 360
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 640 x 180
11:29:14 T:3046076416   DEBUG: Previous line repeats 1 times.
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 1280 x 360
11:29:14 T:3046076416   DEBUG: GL: Creating YUV NPOT texture of size 640 x 180
11:29:14 T:3046076416   DEBUG: Previous line repeats 1 times.
11:29:14 T:3046076416   DEBUG: CGUIInfoManager::SetCurrentMovie(/media/big_buck_bunny_720p_surround.avi)
11:29:14 T:2968212576   DEBUG: CDVDPlayer::HandleMessages - player started 2
11:29:14 T:2968212576   DEBUG: CDVDPlayer::SetCaching - caching state 0
11:29:14 T:2884416608   DEBUG: CDVDPlayerAudio - CDVDMsg::GENERAL_RESYNC(32000.000000, 1)
11:29:14 T:2884416608   DEBUG: CDVDPlayerAudio:: Discontinuity1 - was:-162486.991802, should be:-162477.491802, error:9.500000
11:29:14 T:2959823968   DEBUG: CDVDPlayerVideo - CDVDMsg::GENERAL_RESYNC(41666.600000, 0)
11:29:14 T:3046076416   DEBUG: GetMovieId (/media/big_buck_bunny_720p_surround.avi), query = select idMovie from movie where idFile=4
11:29:14 T:3046076416   DEBUG: GetEpisodeId (/media/big_buck_bunny_720p_surround.avi), query = select idEpisode from episode where idFile=4
11:29:14 T:3046076416   DEBUG: GetMusicVideoId (/media/big_buck_bunny_720p_surround.avi), query = select idMVideo from musicvideo where idFile=4

**ls -l /dev/{ump,disp,cedar_dev,mali}**
>crw-------    1 root     root      150,   0 Jan  1  1970 /dev/cedar_dev
crw-------    1 root     root      252,   0 Jan  1  1970 /dev/disp
crw-rw----    1 root     video     244,   0 Jan  1  1970 /dev/mali
crw-rw----    1 root     video     245,   0 Jan  1  1970 /dev/ump

regards
MichaeL

**Comment by tomlohave** [comment]
Closing, no more activity ;)
