### ISSUE TITLE
update python to 2.7.9

### ISSUE THREAD

**Issue by djack42** [OpenBricks/openbricks#46]
it seems that python 2.7.8 and earlier version have some problem connecting to ssl servers With pyopenssl
I have this issue with sickrage and according to this issue, the problem is due to python and pyopenssl versions : https://github.com/SiCKRAGETV/sickrage-issues/issues/1231#issuecomment-96016081 
Can you upgrade these packages please ?

**Comment by warped-rudi** [comment]
I have just merged our development branch into master, which - besides a lot of other updates - contains python 2.7.9
