### ISSUE TITLE
geexbox-xbmc-imx6-cuboxi/xbmc broken dependencies

### ISSUE THREAD

**Issue by siavashs** [OpenBricks/openbricks#48]
I did a ```opkg upgrade``` today and noticed that xbmc stopped working:
```
root@geexbox:~$ /usr/bin/runxbmc --standalone -fs -l /var/run/lirc/lircd
/usr/lib/xbmc/xbmc.bin: error while loading shared libraries: libgcrypt.so.11: cannot open shared object file: No such file or directory

root@geexbox:~$ ls -l /usr/lib/libgcrypt.so*
lrwxrwxrwx    1 root     root            19 Apr 30 11:01 /usr/lib/libgcrypt.so -> libgcrypt.so.20.0.2
lrwxrwxrwx    1 root     root            19 Apr 30 11:01 /usr/lib/libgcrypt.so.20 -> libgcrypt.so.20.0.2
-rwxr-xr-x    1 root     root        613264 Apr 29 21:39 /usr/lib/libgcrypt.so.20.0.2
```

**Comment by tomlohave** [comment]
does it work creating a symling with new version libgcrypt ?
did you try to force reinstall xbmc ?

**Comment by siavashs** [comment]
They are not ABI compatible:
```
root@geexbox:~$ ln -s /usr/lib/libgcrypt.so /usr/lib/libgcrypt.so.11
root@geexbox:~$ /usr/bin/runxbmc --standalone -fs -l /var/run/lirc/lircd
/usr/lib/xbmc/xbmc.bin: /lib/libgcrypt.so.11: version `GCRYPT_1.2' not found (required by /lib/libmicrohttpd.so.10)
```
I think reinstalling xbmc will not fix it.

**Comment by tomlohave** [comment]
Le 30/04/2015 12:12, Siavash Safi a écrit :
> They are not ABI compatible:
>
> |root@geexbox:~$ ln -s /usr/lib/libgcrypt.so /usr/lib/libgcrypt.so.11
> root@geexbox:~$ /usr/bin/runxbmc --standalone -fs -l /var/run/lirc/lircd
> /usr/lib/xbmc/xbmc.bin: /lib/libgcrypt.so.11: version `GCRYPT_1.2' not found (required by /lib/libmicrohttpd.so.10)
> |
>
> I think reinstalling xbmc will not fix it.
Indeed,
There were massive changes (devel to master merge).
I guess the easy solution is to install a new snapshot
Else you can try to reinstall all impacted packages : libmicrohttpd, 
xbmc and so on
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenBricks/openbricks/issues/48#issuecomment-97728365>.
>


-- 
www.geexbox.org
mailto:tomlohave@openbricks.org

**Comment by warped-rudi** [comment]
It looks like the packages affected by this are:

```
libs/eet
libs/libaacs
libs/libmicrohttpd
libs/libssh
misc/weechat
multimedia/libbdplus
multimedia/vlc
net/netatalk
net/networkmanager
net/wpa-supplicant
system/cups
x11/xorg-server
```

@tomlohave : If we bump PKG_REV for those, opkg should offer them for upgrade as well and everything should be O.K.

**Comment by warped-rudi** [comment]
I've done this in 0a4bd08bec8ef074e0f3e274963ab9719ef52e9f. In theory opkg should offer upgrades for the components using libgcrypt after the next build round.

**Comment by warped-rudi** [comment]
This is not an issue anymore. Closing.
