### ISSUE TITLE
Hummingboard leds not compatible with cuboxi version

### ISSUE THREAD

**Issue by djack42** [OpenBricks/openbricks#49]
I think that hummingboard is not compatible with cuboxi leds, i got errors in journald at startup and i can't use them.
It's low priority and i don't know how it works so i can't really help with PR, i just thought i had to report it.
Keep up the good work.

**Comment by warped-rudi** [comment]
AFAIK, the two LEDs on the Hummingboard are not controllable via software. One is hardwired to the power rail and the other to the network controller's activity output. There are two led nodes under /sys/class/leds/ , but they don't do anything. So simplest thing would be do change our script to exit without doing anything when the LED is not present. I'll have a look...

**Comment by warped-rudi** [comment]
Done in 923043c0253b6c32d2a572f66103db5f3c7d8ba9
