### ISSUE TITLE
geexbox-kodi-imx6-cuboxi: ass subtitles not working - dependancy problem

### ISSUE THREAD

**Issue by djack42** [OpenBricks/openbricks#52]
Hi,
In the geexbox-kodi-imx6-cuboxi snaphot, when playing a mkv file with embedded ass subtitles, no subtitles are displayed, srt subtitles are working though.
That problem has been seen on the last 2 builds :
* http://download.geexbox.org/snapshots/geexbox-kodi-imx6-cuboxi/20150725/
* http://download.geexbox.org/snapshots/geexbox-kodi-imx6-cuboxi/20150801/ (currently latest)

Here is the log when kodi plays the mkv :
https://gist.github.com/djack42/d62b1beca965318dc04f#file-geexbox-kodi-libass-log

The problem seems to be an incompatible libass, I tried to force a reinstall of that package but nothing changed and according to http://upstream.rosalinux.ru/compat_reports/libass/0.10.0_to_0.10.1/abi_compat_report.html, 1 symbol have been added, and it the one required :(

I'm really happy to see kodi on my hummingboard with geexbox by the way.
Keep up the good work :)

**Comment by djack42** [comment]
I couldn't build the entire distro (my first time) but I managed to build the new version of libass, replaced it on my current geexbox install and ssa subtitles are finaly working.

I guess you could merge into master now, the buildbot is going to rebuild kodi-imx6 soon.
thx.

btw where can I have support to build a fork of devel ?
I did tried on a fresh ubuntu x64,
did ./script/loadcfg geexbox-kodi-imx6-cuboxi,
then make but it was not going all the way until I tried make doc first (xsltproc failed somehow).
thx again

**Comment by tomlohave** [comment]
Le 03/08/2015 21:35, djack42 a écrit :
> I couldn't build the entire distro (my first time) but I managed to
> build the new version of libass, replaced it on my current geexbox
> install and ssa subtitles are finaly working.
>
> I guess you could merge into master now, the buildbot is going to
> rebuild kodi-imx6 soon.
> thx.

We can cheery pick this commit, but we have others commits that can be 
problematic in devel branch..

> btw where can I have support to build a fork of devel ?
Here
> I did tried on a fresh ubuntu x64,
> did ./script/loadcfg geexbox-kodi-imx6-cuboxi,

./scripts/loadcfg geexbox-kodi-imx6-cuboxi
> then make but it was not going all the way until I tried make doc first
> (xsltproc failed somehow).
Can you post the exact problem ?
you did "make" and nothing or did you get something on the terminal ?
> thx again

Cheers !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenBricks/openbricks/issues/52#issuecomment-127381726>.
>


-- 
www.geexbox.org
mailto:tomlohave@openbricks.org

**Comment by djack42** [comment]
I'm sorry, I didn't log the first build output, but I can explain step by step what I did to continue the build at that point (I'm still building)

0. setting up a fresh ubuntu 15.04 x64 vm in virtualbox
1. forked openbricks devel branch
2. ./scripts/loadcfg geexbox-kodi-imx6-cuboxi
 I had to enable some packages manually at the end (the one recently added)
3. make
 at that point, it was building for a while and while building libxslt (or libexslt idk), a step with xsltproc failed trying to install some doc.
it was like that log (not mine) but just after the line "Making install in doc", there was the following error : recipe for target 'xsltproc.1' failed
4. after googling i without result, I tried "make doc"
This process downloaded, build and installed more than 1Go of doc tools on my system.
5. I did "make" again, it is still building but I succeeded building that lib

I think that there is a tool installed by "make doc" required to build but not automatically installed. leading to that error.

**Comment by djack42** [comment]
I found out for the 8. it's a bug in the swig tool used in the build of kodi, replacing any ".c"  by ".xml" in the full filename given as output file.
In xbmc/codegenerator.mk, the following rule :
 > $(GENDIR)/%.xml: %.i $(SWIG) $(JAVA) $(GENERATE_DEPS)
 >   mkdir -p $(GENDIR)
 >   $(SWIG) -w401 -c++ -o $@ -xml -I$(TOPDIR)/xbmc -xmllang python $<

replaced by the following is working :
 > SWIG_TEMP_OUTPUT_XML = /tmp/swig_output.xml
 > $(GENDIR)/%.xml: %.i $(SWIG) $(JAVA) $(GENERATE_DEPS)
 >   mkdir -p $(GENDIR)
 >   $(SWIG) -w401 -c++ -o $(SWIG_TEMP_OUTPUT_XML) -xml -I$(TOPDIR)/xbmc -xmllang python $<
 >   mv $(SWIG_TEMP_OUTPUT_XML) $@

I double checked with a filename containing some ".c" :
 > SWIG_TEMP_OUTPUT_XML = /tmp/swig_.cou.ctput.xml
and I saw :
 > ls /tmp/swig_*
 > /tmp/swig_.xmlou.xmltput.xml

At this point, I'd create an issue on the github of swig, but maybe you have another solution in mind.

**Comment by tomlohave** [comment]
Can't reproduce this, feel free to re-open in case you still have the problem
