### ISSUE TITLE
libCEC 3.0

### ISSUE THREAD

**Issue by unixer** [OpenBricks/openbricks#53]
Hi 
hi tried to compile libcec versione 3.0.0
with these options
#!/bin/sh

. config/options
get_meta $1
export MAKEFLAGS=-j1

cd $PKG_BUILD_DIR

if [ "$TARGET_MACHINE" = cubox ]; then
   EXTRA_CMAKE_OPTS="-DHAVE_IMX_API=1"
else
   EXTRA_CMAKE_OPTS="-DHAVE_IMX_API=0"
fi

if [ "$TARGET_MACHINE" = raspberrypi ] || \
   [ "$TARGET_MACHINE" = raspberrypi2 ]; then
   export CXXFLAGS="$CXXFLAGS \
   -I$SYSROOT_PREFIX/usr/local/include/interface/vcos/pthreads/ \
   -I$SYSROOT_PREFIX/usr/local/include/interface/vmcs_host/linux \
   -I$SYSROOT_PREFIX/usr/local/include/interface/vchiq_arm"

   # detecting RPi support fails without -lvchiq_arm
   export LDFLAGS="$LDFLAGS -lvchiq_arm"
fi
mkdir build || true && cd build
cmake -DCMAKE_TOOLCHAIN_FILE=$CMAKE_CONF \
      -DBUILD_SHARED_LIBS=1 \
      -DSKIP_PYTHON_WRAPPER:STRING=1 \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_INSTALL_LIBDIR=/usr/lib \
      -DCMAKE_INSTALL_LIBDIR_NOARCH=/usr/lib \
      -DCMAKE_INSTALL_PREFIX_TOOLCHAIN=$SYSROOT_PREFIX/usr \
      -DCMAKE_PREFIX_PATH=$SYSROOT_PREFIX/usr \
      $EXTRA_CMAKE_OPTS \
      ..

make
make_install

But i have these error

 BUILD    libcec
toolchain already installed, skipping...
systemd already installed, skipping...
liblockdev already installed, skipping...
platform already installed, skipping...
systemd already installed, skipping...
liblockdev already installed, skipping...
raspberrypi-userland already installed, skipping...
mkdir: impossibile creare la directory "build": File già esistente
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/bin/armv7-openbricks-linux-gnueabihf-gcc
-- Check for working C compiler: /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/bin/armv7-openbricks-linux-gnueabihf-gcc -- broken
CMake Error at /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "/root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/bin/armv7-openbricks-linux-gnueabihf-gcc"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /root/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.0/build/CMakeFiles/CMakeTmp

  Run Build
  Command:/root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/bin/make
  "cmTryCompileExec1758561157/fast"

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/bin/make -f
  CMakeFiles/cmTryCompileExec1758561157.dir/build.make
  CMakeFiles/cmTryCompileExec1758561157.dir/build

  make[1]: Entering directory
  '/media/disk/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.0/build/CMakeFiles/CMakeTmp'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/bin/cmake -E
  cmake_progress_report
  /root/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.0/build/CMakeFiles/CMakeTmp/CMakeFiles
  1

  Building C object
  CMakeFiles/cmTryCompileExec1758561157.dir/testCCompiler.c.o

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/bin/armv7-openbricks-linux-gnueabihf-gcc
  -O2 -march=armv7-a -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated
  -mtune=cortex-a7 -ffast-math -fPIC -fgraphite-identity
  -ftree-loop-distribution -floop-interchange -floop-strip-mine -floop-block
  -mfloat-abi=hard -mfpu=neon -Wall -pipe -g -D_FILE_OFFSET_BITS=64
  -D_LARGEFILE_SOURCE
  -I/root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/local/include
  -I/root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/include
  -o CMakeFiles/cmTryCompileExec1758561157.dir/testCCompiler.c.o -c
  /root/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.0/build/CMakeFiles/CMakeTmp/testCCompiler.c

  Linking C executable cmTryCompileExec1758561157

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/bin/cmake -E
  cmake_link_script CMakeFiles/cmTryCompileExec1758561157.dir/link.txt
  --verbose=1

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/bin/armv7-openbricks-linux-gnueabihf-gcc
  -O2 -march=armv7-a -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated
  -mtune=cortex-a7 -ffast-math -fPIC -fgraphite-identity
  -ftree-loop-distribution -floop-interchange -floop-strip-mine -floop-block
  -mfloat-abi=hard -mfpu=neon -Wall -pipe -g -D_FILE_OFFSET_BITS=64
  -D_LARGEFILE_SOURCE
  -I/root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/local/include
  -I/root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/include
  -L/root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/lib
  -L/root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib
  -L/root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/local/lib
  -lvchiq_arm CMakeFiles/cmTryCompileExec1758561157.dir/testCCompiler.c.o -o
  cmTryCompileExec1758561157 -rdynamic

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `sem_post'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_log_impl'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_generic_mem_free'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_thread_attr_init'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_global_lock'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_global_unlock'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_abort'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `sem_getvalue'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_log_register'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_generic_mem_alloc'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `sem_wait'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `sem_init'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_thread_join'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_pthreads_logging_assert'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_pthreads_map_errno'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `sem_destroy'

  /root/SifBoX/build/build.raspberrypi2.eglibc/toolchain/armv7-openbricks-linux-gnueabihf/sysroot/usr/lib/libvchiq_arm.so:
  undefined reference to `vcos_thread_create'

  collect2: error: ld returned 1 exit status

  CMakeFiles/cmTryCompileExec1758561157.dir/build.make:91: recipe for target
  'cmTryCompileExec1758561157' failed

  make[1]: Leaving directory
  '/media/disk/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.0/build/CMakeFiles/CMakeTmp'

  make[1]: *** [cmTryCompileExec1758561157] Error 1

  Makefile:117: recipe for target 'cmTryCompileExec1758561157/fast' failed

  make: *** [cmTryCompileExec1758561157/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)

-- Configuring incomplete, errors occurred!

**Comment by tomlohave** [comment]
Le 25/09/2015 15:33, Unixer a écrit :
> Hi
Hi,
> hi tried to compile libcec versione 3.0.0

Why version 3.0.0 ?

Our version (from master) is 3.0.1
Is there a problem with this version ?

https://github.com/OpenBricks/openbricks/blob/master/packages/libs/libcec3/meta


-- 
www.geexbox.org
mailto:tomlohave@openbricks.org

**Comment by unixer** [comment]
ops :( 
sorry 
i Tried with 3.0.1
thanks

**Comment by unixer** [comment]
I have these error
Scanning dependencies of target cec
make[3]: Leaving directory '/media/disk/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.1+re8506b3/.build'
make[3]: Entering directory '/media/disk/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.1+re8506b3/.build'
[  2%] Building CXX object src/libcec/CMakeFiles/cec.dir/CECClient.cpp.o
[  5%] [  7%] Building CXX object src/libcec/CMakeFiles/cec.dir/LibCEC.cpp.o
Building CXX object src/libcec/CMakeFiles/cec.dir/CECProcessor.cpp.o
[ 10%] Building CXX object src/libcec/CMakeFiles/cec.dir/LibCECC.cpp.o
[ 13%] [ 15%] Building CXX object src/libcec/CMakeFiles/cec.dir/adapter/RPi/RPiCECAdapterDetection.cpp.o
Building CXX object src/libcec/CMakeFiles/cec.dir/adapter/RPi/RPiCECAdapterCommunication.cpp.o
In file included from /root/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.1+re8506b3/src/libcec/adapter/RPi/RPiCECAdapterCommunication.cpp:37:0:
/root/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.1+re8506b3/src/libcec/adapter/RPi/RPiCECAdapterCommunication.h:45:47: fatal error: interface/vmcs_host/vc_cecservice.h: No such file or directory
 #include <interface/vmcs_host/vc_cecservice.h>
                                               ^
compilation terminated.
src/libcec/CMakeFiles/cec.dir/build.make:169: recipe for target 'src/libcec/CMakeFiles/cec.dir/adapter/RPi/RPiCECAdapterCommunication.cpp.o' failed
make[3]: *** [src/libcec/CMakeFiles/cec.dir/adapter/RPi/RPiCECAdapterCommunication.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/root/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.1+re8506b3/src/libcec/adapter/RPi/RPiCECAdapterDetection.cpp:40:47: fatal error: interface/vmcs_host/vc_cecservice.h: No such file or directory
 #include <interface/vmcs_host/vc_cecservice.h>
                                               ^
compilation terminated.
src/libcec/CMakeFiles/cec.dir/build.make:146: recipe for target 'src/libcec/CMakeFiles/cec.dir/adapter/RPi/RPiCECAdapterDetection.cpp.o' failed
make[3]: *** [src/libcec/CMakeFiles/cec.dir/adapter/RPi/RPiCECAdapterDetection.cpp.o] Error 1
make[3]: Leaving directory '/media/disk/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.1+re8506b3/.build'
CMakeFiles/Makefile2:227: recipe for target 'src/libcec/CMakeFiles/cec.dir/all' failed
make[2]: *** [src/libcec/CMakeFiles/cec.dir/all] Error 2
make[2]: Leaving directory '/media/disk/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.1+re8506b3/.build'
Makefile:117: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/media/disk/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.1+re8506b3/.build'
make: *** [rootfs] Errore 2

**Comment by tomlohave** [comment]
Le 25/09/2015 19:38, Unixer a écrit :
> I have these error
[..]

/root/SifBoX/build/build.raspberrypi2.eglibc/libcec-3.0.1+re8506b3/src/libcec/adapter/RPi/RPiCECAdapterCommunication.h:45:47: 

> fatal error: interface/vmcs_host/vc_cecservice.h: No such file or directory
missing dep ?
https://github.com/OpenBricks/openbricks/blob/master/config/platforms/arm/bcm2708/packages/libcec3/meta

-- 
www.geexbox.org
mailto:tomlohave@openbricks.org

**Comment by unixer** [comment]
now is Ok  with
cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
      -DCMAKE_FIND_ROOT_PATH=$LIB_PREFIX \
      -DSWIG_DIR=$TOOLCHAIN/bin \
      -DSKIP_PYTHON_WRAPPER:STRING=1 \
      -DBUILD_SHARED_LIBS=1 \
      $EXTRA_CONFIG \
      -DCMAKE_CXX_FLAGS="$EXTRA_INCLUDES" \
      -DCMAKE_PREFIX_PATH=$SYSROOT_PREFIX/usr \
      -DPYTHON_LIBRARY="$LIB_PREFIX" \
      -DPYTHON_INCLUDE_DIR="$LIB_PREFIX/include/python2.7" \
      ..

**Comment by tomlohave** [comment]
Le 25/09/2015 19:55, Unixer a écrit :
> now is Ok with
> cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
> -DCMAKE_FIND_ROOT_PATH=$LIB_PREFIX \
> -DSWIG_DIR=$TOOLCHAIN/bin \
> -DSKIP_PYTHON_WRAPPER:STRING=1 \
> -DBUILD_SHARED_LIBS=1 \
> $EXTRA_CONFIG \
> -DCMAKE_CXX_FLAGS="$EXTRA_INCLUDES" \
> -DCMAKE_PREFIX_PATH=$SYSROOT_PREFIX/usr \
> -DPYTHON_LIBRARY="$LIB_PREFIX" \
> -DPYTHON_INCLUDE_DIR="$LIB_PREFIX/include/python2.7" \
> ..
>
>
great.
Closing.

-- 
www.geexbox.org
mailto:tomlohave@openbricks.org
