### ISSUE TITLE
Home cinema often shutdown when exiting kodi screensaver

### ISSUE THREAD

**Issue by djack42** [OpenBricks/openbricks#54]
Hi,
I'm submitting this issue here because I don't know if it is a kodi problem or a geexbox problem, I hope someone will be able to find a solution.

The problem is happening when geexbox goes into screensaver mode (I'm using dim), the home cinema stays connected, but when I wake up geexbox using my tv remote, the home cinema is shutting down most of the times.
I think it receives a bad signal when kodi wakes up and think that the theatre mode is turned off or that the tv is turned off. 

I'm using the distrib geexbox kodi cuboxi on a humminboard (build devel-20150725-rb2f16a7-imx6, opkg up to date) and I would like to avoid reinstalling if there is nothing better in the recent builds.
It is linked to my Sony TV with a HDMI cable and my TV is also linked to my Sony Home Cinema using HDMI ARC. The Home Cinema as an option to shutdown when the TV shutdown, and wakes up when I activate the THEATRE mode.

Thank you

**Comment by warped-rudi** [comment]
There have been some changes in the CEC area in the mean time, but have no idea if they affect this. It's certainly a generic Kodi issue. Did you play with the "Put devices in standby when activating the screensaver" and "Wake devices when deactivation the screensaver" options?

**Comment by tomlohave** [comment]
Closing, no more infos
