### ISSUE TITLE
Raspberry pi 3

### ISSUE THREAD

**Issue by unixer** [OpenBricks/openbricks#57]
Hi,
when the new Platform ?

**Comment by warped-rudi** [comment]
Hmm. At the moment I don't really have a plan. I would have to buy another device and I already got about 10 ARM boards...
It looks like the Cortex-A53 used in the Pi3 can run in 32bit mode. So we might probably get away with the Pi2 image plus updated kernel and *.dtb files...

**Comment by unixer** [comment]
Hi 
i update the Linux at the version 4.1.10 and add Patches for bcm2710 - Raspberry 3
now i Update Raspberry firmware
in jarvis branch

**Comment by warped-rudi** [comment]
WHY THE HELL ARE YOU PUSHING THAT TO JARVIS !!!
CAN'T YOU CREATE YOU OWN BRANCH FOR THIS OR AT LEAST ASK !!!

**Comment by unixer** [comment]
Ops sorry
delete it please
and i push in other branch

**Comment by tomlohave** [comment]
Le 24/03/2016 18:19, Unixer a écrit :
Hi Unixer

I can understand why Rudi is so angry.
As he said, you can push in a new branch if you want
I have forced pushed to jarvis to roolback in a sane state.
We are happy if someone want to help us, but please keep in mind that we 
are committing only package by package. It helps us to track problems if 
any.

You have your own branch now (jarvis-unixer)
If you want to discuss about your commit, feel free.
To begin,

431f91cd18109f2c96707ab7337729eeb87f6e89 and 
0f958e519a388d9b0c24664d7c2705a7be38794b

are too big, please explain all your modifications or split them to help 
us to understand why you need to change / create new files like 
firmware, why pvr package is modified, and so on.

> Ops sorry
> delete it please
> and i push in other branch
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenBricks/openbricks/issues/57#issuecomment-200934758>
>


-- 
www.geexbox.org
mailto:tomlohave@openbricks.org

**Comment by tomlohave** [comment]
A quick look of files you have added (firmware/radeon/* ) are already present using our package firmware-graphics-radeon

**Comment by unixer** [comment]
Ok 

Tuesday will divide all the files with the appropriate explanations

Happy Holidays

 

 

Nota di riservatezza - D. Lgs n. 196 del 30.06.2003 - ( Codice Privacy ):

In ottemperanza e nel pieno rispetto delle specifiche indicazioni del decreto di cui sopra, Vi informiamo che i Vostri dati sono trattati nella piena tutela dei Vostri diritti, della Vostra riservatezza. Si ricorda che è sufficiente inviare un messaggio al mittente del presente e-mail con oggetto "CANCELLA o RIMUOVI" per poter essere rimossi dall'archivio o per avere informazioni e/o chiarimenti. Il presente messaggio, corredato dai relativi allegati (ove presenti), contiene informazioni da considerarsi strettamente riservate, ed è destinato esclusivamente al destinatario sopra indicato, il quale è l'unico autorizzato ad usarlo, copiarlo e, sotto la propria responsabilità, diffonderlo. Chiunque ricevesse questo messaggio per errore o comunque lo leggesse senza esserne legittimato è avvertito che trattenerlo, copiarlo, divulgarlo, distribuirlo a persone diverse è severamente proibito ed è pregato di rinviarlo immediatamente al mittente distruggendone l'originale. Grazie.
Notice to recipient: This e-mail is strictly confidential and meant for only the intended recipient of the transmission. If you received this e-mail by mistake, any review, use, dissemination, distribution, or copying of this e-mail is strictly prohibited. Please notify us immediately of the error by return e-mail and please delete this message from your system. Thank you in advance for your cooperation. 

 

Da: Thomas Genty [mailto:notifications@github.com] 
Inviato: giovedì 24 marzo 2016 18:45
A: OpenBricks/openbricks
Cc: Unixer
Oggetto: Re: [openbricks] Raspberry pi 3 (#57)

 

Le 24/03/2016 18:19, Unixer a écrit :
Hi Unixer

I can understand why Rudi is so angry.
As he said, you can push in a new branch if you want
I have forced pushed to jarvis to roolback in a sane state.
We are happy if someone want to help us, but please keep in mind that we 
are committing only package by package. It helps us to track problems if 
any.

You have your own branch now (jarvis-unixer)
If you want to discuss about your commit, feel free.
To begin,

431f91cd18109f2c96707ab7337729eeb87f6e89 and 
0f958e519a388d9b0c24664d7c2705a7be38794b

are too big, please explain all your modifications or split them to help 
us to understand why you need to change / create new files like 
firmware, why pvr package is modified, and so on.

> Ops sorry
> delete it please
> and i push in other branch
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> < <https://github.com/OpenBricks/openbricks/issues/57#issuecomment-200934758> https://github.com/OpenBricks/openbricks/issues/57#issuecomment-200934758>
>


-- 
 <http://www.geexbox.org> www.geexbox.org
 <mailto:tomlohave@openbricks.org> mailto:tomlohave@openbricks.org

**Comment by warped-rudi** [comment]
In c5f66957a2de779d55570b3ecdd13eb3df079660 .. 4de5eda338a50484d529504259b02f4573e2dc97 I've bumped the raspberry kernel/firmware/userland to the lastest versions. Thus, the bcm2709-raspberrypi2 might work with the Raspberry 3 (untested).

**Comment by warped-rudi** [comment]
O.K, I can now confirm that our RaspberryPi2 image will work on the Raspberry3. For WLAN support, f55354dff9b733038e9701ce082f3ea4312fde3b and 44b5b4563941822f9b1d1bfb7f88614e25235238 are required. Bluetooth is not working at the moment, but the hardware appears quite similar to Cubox-i. Hopefully, the BCM43438 is better than the BCM4329/BCM4330 used in those devices...

**Comment by warped-rudi** [comment]
With today's commits Bluetooth at least does something... It does not completely kill WLAN (as on the Cubox-i), but seems to degrade the WLAN performance. Therefore, it's disabled by default.

@tomlohave :
With the newly patched bluez, brcm-patchram-plus is no longer needed. Firmware uploading to the Broadcom chips is now done by the _hciattach_ tool on both RPi3 and Cubox-i platforms.

**Comment by warped-rudi** [comment]
It seems that some work has been started to enable 64bit mode. See https://github.com/raspberrypi/firmware/issues/579 But I think, I'll let that settle a bit and see if native 64bit armv8 code will boost performance enough to justify the effort of introducing a complete new platform.

BTW, the serial console on the RPi3 is currently not set up correctly. I'll investigate/fix that later this week.

**Comment by warped-rudi** [comment]
With 75db8349fb98449211a3a2748e09d3e18a8cea16 and 67869e8a3cc4179ab76f0a9ecef3c76032c62aff we get a little bit more convenient handling of the UART switching. In general, the mini-UART (/dev/ttyS0) is rather problematic. Therefore we don't get a serial console on the RaspberryPi 3 by default. In order to activate it, there are three possibilities:

1. Uncomment _enable_uart=1_ (optionally, enable _force_turbo=1_)
2. Activate the _pi3-miniuart-bt_ overlay (set _enable_uart=1_ / _force_turbo=1_ if Bluetooth is needed)
3. Activate the _pi3-disable-bt_ overlay (Bluetooth not needed)

Approach 1. uses /dev/ttyS0 as console (115200,7,n,1), while 2. and 3. will use /dev/ttyAMA0 (115200,8,n,1). If _force_turbo=1_ is not activated, the ARM cores don't run at their maximum speed. If it is, they are slightly overclocked. So be sure to have a good power supply and check for overheating! W.r.t. Bluetooth, keep in mind that the systemd service to upload the firmware and enable the HCI device  (bluetooth-setup.service) is masked by default.

I'll close this topic as I think the RaspberryPi 3 is now sufficiently supported by our RaspberryPi 2 image. As long as we are not sure that an armv8/aarch64 approach will give significant benefits, I think we should leave it this way. But if someone want's to play with that: Go ahead and let us know about the results!

@unixer : Does the RapsberryPi 3 work for you now?
