### ISSUE TITLE
Stream audio to linux box?

### ISSUE THREAD

**Issue by HolgerJeromin** [OpenBricks/openbricks#59]
I am planing a strange setup here. :-)
Cubox-i next to a beamer with only a network cable. My Problem is the audio. 
Is there a possibility to stream Audio to my Debian box (which has good speaker, but only a small Monitor).

I can think of streaming with Bluetooth or Network (Pulseaudio?).
Bluetooth was problematic with Cubox-i in the beginning... 
Is it possible to configure GeeXbox to such a setup?

**Comment by tomlohave** [comment]
Le 16/05/2016 21:45, Holger Jeromin a écrit :
> I am planing a strange setup here. :-)
> Cubox-i next to a beamer with only a network cable. My Problem is the
> audio.
> Is there a possibility to stream Audio to my Debian box (which has good
> speaker, but only a small Monitor).
>
> I can think of streaming with Bluetooth or Network (Pulseaudio?).
> Bluetooth was problematic with Cubox-i in the beginning...
> Is it possible to configure GeeXbox to such a setup?
Bluetooth is still a problem.
Pulseaudio is packaged but I have no experience for such thing
Now we have mpd too. It should do what you want. (if it's only for music)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenBricks/openbricks/issues/59>
>


-- 
www.geexbox.org
mailto:tomlohave@openbricks.org

**Comment by HolgerJeromin** [comment]
Thanks for your answer. I will try that.
