### ISSUE TITLE
menuconfig: Can't get configtools.

### ISSUE THREAD

**Issue by junland** [OpenBricks/openbricks#65]
I've tried running `make menuconfig` however it can't get passed `configtools`, I've tried this on Fedora 30 and Ubuntu 19.04. Below is the output of what I did.

```
[vagrant@project-gemstone ~]$ git clone https://github.com/OpenBricks/openbricks.git
Cloning into 'openbricks'...
remote: Enumerating objects: 892, done.
remote: Counting objects: 100% (892/892), done.
remote: Compressing objects: 100% (429/429), done.
remote: Total 171998 (delta 707), reused 599 (delta 462), pack-reused 171106
Receiving objects: 100% (171998/171998), 192.40 MiB | 11.55 MiB/s, done.
Resolving deltas: 100% (112696/112696), done.
Checking out files: 100% (12049/12049), done.
[vagrant@project-gemstone ~]$ ls
openbricks
[vagrant@project-gemstone ~]$ cd openbricks/
[vagrant@project-gemstone openbricks]$ make menuconfig
scripts/kconfiginit
  GET      kconfig-frontends
Computing MD5 check for sources/kconfig-frontends/kconfig-frontends-3.12.0.0.tar.xz ... OK
  CLEAN    kconfig-frontends
  UNPACK   kconfig-frontends
## Applying patch: packages/misc/kconfig-frontends/patches/10-frontends_gconf_Makefile_in.patch
      GET      configtools
\nCan't get configtools sources, trying on OpenBricks server...
```

**Comment by warped-rudi** [comment]
Our server is currently down due to a hardware failure. Until this is resolved, I'm afraid you won't be able to do anything. Sorry.

**Comment by junland** [comment]
@warped-rudi Thanks, Is there any mailing lists / IRC for this project so I can keep track of the progress of the project / updates on the server failure?

**Comment by tomlohave** [comment]
Le 16/07/2019 à 15:50, John Unland a écrit :
Hello,

> @warped-rudi <https://github.com/warped-rudi> Thanks, Is there any 
> mailing lists / IRC for this project so I can keep track of the progress 
no more active mailing  lists even if it should work.
> of the project / updates on the server failure?

Working on it , server rebooted but still no access.
